// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var s = "这种写法是正常的";

function fn(s) {
  return "" + s;
}

function fn_1(s) {
  return s;
}

function fn_2(s) {
  return s + "";
}

function fn_3(s) {
  return s + "";
}

var s1 = "" + s;

var s2 = "\xe8\xbf\x99\xe9\x87\x8c\xe7\x9a\x84\xe5\xb0\xb1\xe4\xbc\x9a\xe4\xb9\xb1\xe7\xa0\x81";

var s4 = "\xe5\x87\xba\xe9\x97\xae\xe9\xa2\x98\xe4\xba\x86";

var s5 = "\xe5\x87\xba\xe9\x97\xae\xe9\xa2\x98\xe4\xba\x86";

var s7 = "\xe5\x87\xba\xe9\x97\xae\xe9\xa2\x98\xe4\xba\x86";

var s8 = "\xf0\x9f\x98\x80";

var s10 = "\xf0\x9f\x98\x80";

var s11 = "\xf0\x9f\x98\x80";

var s3 = "没问题";

var s6 = "没问题";

var s9 = "😀";

exports.s = s;
exports.fn = fn;
exports.fn_1 = fn_1;
exports.fn_2 = fn_2;
exports.fn_3 = fn_3;
exports.s1 = s1;
exports.s3 = s3;
exports.s6 = s6;
exports.s9 = s9;
exports.s2 = s2;
exports.s4 = s4;
exports.s5 = s5;
exports.s7 = s7;
exports.s8 = s8;
exports.s10 = s10;
exports.s11 = s11;
/* No side effect */
